# Generated by Django 2.2.4 on 2019-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('Direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
