# Generated by Django 2.2.4 on 2019-11-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test_burn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('Apellidos', models.CharField(max_length=150, verbose_name='Nombres')),
                ('Direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test_burn.Empresa')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
